chat/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path("<str:username>/", views.chat, name='main_chat')
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home_view, name="home"),
    path("profile/<str:pk>", views.profile, name="profile"),
    # path("create-post", views.create_post, name="create-post"),
    path("account", views.account_view, name="account"),
    path("settings", views.settings_view, name="settings"),
    path("comment", views.comment, name="comment"),
    path("delete-comment/<int:pk>", views.delete_comment, name="delete-comment"),

    path("follow-suggestions", views.follow_suggestions, name="follow-suggestions"),
    path("post/<uuid:pk>", views.post_detail, name="post-detail"),
    path("delete-post/<uuid:pk>", views.delete_post, name="delete-post"),
    path("update-post/<uuid:pk>", views.update_post, name="update-post")
    # path("follow", views.follow_view, name="follow"),



    
]

django_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path("",include("core.urls")),
    path("chat/", include("chat.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

import uuid


User = get_user_model()


class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="profile_image", default="avatar.svg")
    bio = models.TextField(blank=True)
    location = models.CharField(max_length=100)
    online_status = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.user.username
    
    def get_absolute_url(self):
        return reverse('profile', args=[self.user.id])



class Post(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_image")
    title = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    created= models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    liked = models.BooleanField(default=False)

    def __str__(self) -> str:
        return self.title
    
    def get_absolute_url(self):
        return reverse('post-detail', args=[self.id])
    

class Likes(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)
    class Meta:
        verbose_name_plural = "Likes"

    def __str__(self) -> str:
        return self.user.username


class Followers(models.Model):
    follower = models.ForeignKey(User, on_delete=models.CASCADE, related_name="followers")
    following = models.ForeignKey(User, on_delete=models.CASCADE, related_name="following")
    class Meta:
        verbose_name_plural = "Follows"

    def __str__(self) -> str:
        return self.follower.username
    

class Comment(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created"]

    def __str__(self) ->str:
        return self.body

core/forms.py
from django import forms
from .models import Post, Profile


class CreatePostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ["image", "title", "description"]


class CreateProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ["image", "bio", "location" ]

core/views.py
import random
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Q

from .models import Post, Profile, Followers, Likes, Comment
from .forms import CreatePostForm, CreateProfile
from django.contrib.auth.models import User
from django.http import HttpResponse
from django_htmx.http import HttpResponseClientRefresh, HttpResponseClientRedirect


@login_required(login_url="account_login")
def home_view(request):
    page = "home"
    posts = Post.objects.all()
    profile = Profile.objects.get(user=request.user)
        
    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect("home")
    else:
        form = CreatePostForm()

    if request.htmx:
        user = request.user
        try:
            post = Post.objects.get(id=request.POST.get("post_id"))
            
            if Likes.objects.filter(post=post, user=user, liked=True).exists():
                unlike = Likes.objects.get(user=user, post=post, liked=True)
                unlike.delete()
                return HttpResponseClientRefresh()
               
            else:
                like = Likes.objects.create(user=user, post=post, liked=True)
                like.save()
                return HttpResponseClientRefresh()
            
        except:
            return redirect("home")
    
    user = request.user
    request_user_liked_post = [post.id for post in posts if Likes.objects.filter(post=post, user=user, liked=True).exists()] 
            
    user_following = Followers.objects.filter(follower=user).values_list('following__id', flat=True)
    
    user_suggestions = Profile.objects.exclude(user=user.id).exclude(user__in=user_following)
    
    chat_suggestions = Profile.objects.filter(user__in=user_following)
    
    
    try:
        user_suggestions = random.sample(list(user_suggestions), 3)
    except:
        user_suggestions = user_suggestions

    post_comments = {}
    for post in posts:
        comments = Comment.objects.filter(post=post)
        post_comments[post.id] = comments
    
    #shows posts of people followed by request user
    posts = posts.filter(user_id__in=user_following).order_by("-created")
   
    context = {
        "posts": posts,
        "form": form,
        "page": page,
        "profile": profile,
        "request_user_liked_post": request_user_liked_post,
        "user_suggestions": user_suggestions,
        "post_comments": post_comments,
        "chat_suggestions": chat_suggestions
    }
    return render(request, "core/home.html", context)

@login_required(login_url="account_login")
def profile(request, pk):
    user = User.objects.get(username=pk)
    profile = Profile.objects.get(user=user.id)
    posts = Post.objects.filter(user=user)
    followers = Followers.objects.filter(following=user)
    follow = Followers.objects.filter(follower=user)
    
    is_following = False

    if request.method == "POST":
        follower = User.objects.get(username=request.POST.get("user"))
        user_to_follow = request.POST.get("user_to_follow")
        following = User.objects.get(username=user_to_follow)
        if Followers.objects.filter(follower=follower, following=following).exists():
            unfollow = Followers.objects.get(follower=follower, following=following)
            unfollow.delete()
            return redirect("profile", pk=user_to_follow)
        else:
            nwe_follow = Followers.objects.create(follower=follower, following=following)
            nwe_follow.save()
            return redirect("profile", pk=user_to_follow)
    
    
    follower = request.user
    if Followers.objects.filter(follower=follower, following=user).exists():
        is_following = True

    context = {
        "profile": profile,
        "posts" : posts,
        "followers":followers,
        "follow":follow,
        "is_following": is_following
    }
    return render(request, "core/profile.html", context)


@login_required(login_url="account_login")
def account_view(request):
    user = request.user
    if request.method == "POST":
        form = CreateProfile(request.POST, request.FILES)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            return redirect("profile", pk=user.username)
    else:
        form = CreateProfile()
    
    context = {
        "user": user,
        "form": form
    }
    return render(request, "core/account.html", context)
    
@login_required(login_url="account_login")
def settings_view(request):
    user = request.user
    profile = Profile.objects.get(user=user)

    if request.method == "POST":
        form = CreateProfile(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            form.save()
            return redirect("profile", pk=user.username)
    else:
        form = CreateProfile(instance=profile)
    
    context = {
        "form":form,
        "profile": profile
    }
    return render(request, "core/settings.html", context)

@login_required(login_url="account_login")
def follow_suggestions(request):
    user = request.user
    if request.method == "POST":
        follow_suggestion_username = request.POST.get("follow_suggestion_username")
        user_to_follow = User.objects.get(username=follow_suggestion_username)
        follow = Followers.objects.create(follower=user, following=user_to_follow)
        follow.save()
        return HttpResponseClientRefresh()
    
    return render(request, "core/partials/follow_suggestions.html")

@login_required(login_url="account_login")
def post_detail(request, pk):
    user = request.user
    post = get_object_or_404(Post, id=pk)
    profile = get_object_or_404(Profile, user=user)

    likes = Likes.objects.filter(post=post, liked=True)
    
    is_post_liked = Likes.objects.filter(user=user, post=post, liked=True).exists

    comments = post.comment_set.filter(post=post)

    context={
        "post":post,
        "is_post_liked":is_post_liked,
        "likes": likes,
        "comments": comments,
        "profile":profile
    }

    return render(request, "core/post_detail.html", context)


@login_required(login_url="account_login")
def update_post(request, pk):
    post = Post.objects.get(id=pk)

    if request.method == "POST":
        form = CreatePostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect("post-detail", post.id)
    
    else:
        form = CreatePostForm(instance=post)
    
    context = {
        "post": post,
        "form": form
    }

    return render(request, "core/update-post.html", context )

@login_required(login_url="account_login")
def delete_post(request, pk):
    user = request.user
    post = get_object_or_404(Post, id=pk, user=user)
    next_url = request.GET.get("next")

    post.delete()
    
    if next_url:
        return HttpResponseClientRedirect(next_url)
    
    return HttpResponseClientRefresh()
    

@login_required(login_url="account_login")
def comment(request):
    user = request.user
   
    if request.htmx:
        post_id = request.POST.get("post_id")
        post = Post.objects.get(id=post_id)
        body = request.POST.get("body")
        comment = Comment.objects.create(owner=user, post=post, body=body)
        comment.save()
    return HttpResponseClientRefresh()
    
   
@login_required(login_url="account_login")
def delete_comment(request, pk):
    comment = get_object_or_404(Comment, id=pk)
    comment.delete()
    return HttpResponseClientRefresh()

templates/core/account.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}

{% block content %}
<div class="d-flex justify-content-center">
    <div class="card mt-3 " style="width: 30rem;">
        <div class="card-body">
            <h5 class="card-title">Create Profile</h5>
            <div id="image_box">
                <img  src="{% static 'images/avatar.svg' %}" class="card-img-top " alt="...">
            </div>
            <form  method="POST" enctype="multipart/form-data" >
                {% csrf_token %}
                <div  id="image" class="forms-control {% if field.errors %} errors {% endif %} ">
                    <label>{{ form.image.label_tag }}</label>
                    {{ form.image.errors }}
                    {% render_field form.image class="form-control"  name="image" id="id_image"%}
                </div>
      
                <div class="forms-control {% if field.errors %} errors {% endif %} ">
                    <label>{{ form.bio.label_tag }}</label>
                    {{ form.bio.errors }}
                    {% render_field form.bio class="form-control"  name="bio" id="id_bio"%}
                </div>
                
                <div  class="forms-control {% if field.errors %} errors {% endif %} ">
                    <label>{{ form.location.label_tag }}</label>
                    {{ form.location.errors }}
                    {% render_field form.location class="form-control"  name="location" id="id_location"%}
                </div>
      
                <button type="submit" class="btn btn-success mt-2">Create Profile</button>
            </form>
        </div>
    </div>
</div>

<script>
    const imageBox = document.getElementById("image_box")
    const input = document.getElementById("id_image")
    const csrf = document.getElementsByName("csrfmiddelwaretoken")

    input.addEventListener('change', (e)=>{
        const img_data = input.files[0]
        const url = URL.createObjectURL(img_data)
        imageBox.innerHTML = `<img src="${url}" id="image" width=450px >`
    })

</script>
    
{% endblock content %}

    

templates/core/home.html
{% extends '_base.html' %}
{% load static %}
{% load custom_filter %}


{% block css %}
    <link rel="stylesheet" href="{% static 'style/home.css' %}">
{% endblock css %}
    

{% block title %}
Social Book
{% endblock title %}
    

{% block content %}
<div class="container" >
    <div class="post-container">
        {% for post in posts %}
            <div class="cards">
                <div class="card-item card mt-5 mb-3">
                    <div>
                        
                        {% if request.user == post.user %}
                        <button class="btn btn-link dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-ellipsis"></i></button>
                        <ul class="dropdown-menu dropdown-menu-dark">
                            <li>
                                <button hx-delete="{% url 'delete-post' post.id %}" 
                                        hx-confirm="Are you sure you want to delete this post?"
                                        class="dropdown-item" >Delete post
                                </button>
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'update-post' post.id %}">Update Post</a>
                            </li>
                        </ul>
                        {% endif %}
                        <a class="nav-link" >
                            <button type="button" data-bs-toggle="modal" data-bs-target="#carousel">
                                <img id="post_img" src="{{post.image.url}}" class="card-img-top " alt="...">
                            </button>
                        </a> 
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between ">
                            <h5 class="card-title  "><a href="{% url 'profile' post.user.username %}">@{{post.user.username}} </a>| <a href="{{ post.get_absolute_url }}">{{post.title}}</a></h5>
                            <div class="d-flex justify-content-between ">
                                <form id="like-form" hx-post="{% url 'home' %}">
                                    <input id="input" type="hidden" name="post_id" value="{{post.id}}">
                                    {% if post.id in request_user_liked_post %}
                                        <button id="unlike" type="submit" class="btn btn-link "><i class="fa-solid fa-heart fa-xl " style="color: #f2075a;"></i></button>
                                    {% else %}
                                        <button id="like" type="submit" class="btn btn-link "><i class="fa-regular fa-heart fa-xl" style="color: #f2075a;"></i></button>
                                    {% endif %}
                                </form>
                            </div>   
                        </div>

                        <p class="card-text mt-3">{{post.description}}</p>
                        <p class="card-text"><small class="text-body-secondary">{{post.created}}</small></p>

                        <hr>

                        <div id="comment-section "> 
                            <div class="d-flex justify-content-between">
                                <img id="profile_img" src="{{profile.image.url}}" alt="">
                                <form hx-post="{% url 'comment' %}" >
                                    {% csrf_token %}
                                    <input id="post_id" type="hidden" name="post_id" value="{{post.id}}">
                                    <input id="comment_input" class="comment_input" type="text" name="body" placeholder="write your comment..." required>
                                    <button id="comment_button" type="submit" class="btn btn-link "><i class="fa-regular fa-paper-plane"></i></button>
                                </form>
                            </div>
                            {% for comment in post_comments|get_comments:post.id|slice:"5" %}                   
                                {% if comment.owner == request.user  %}
                                   <div id="comment_box" class="comment" >
                                        <a href="{% url 'profile' comment.owner %}"><samp>@{{comment.owner}}</samp></a>
                                        <p>{{comment.body}}
                                                <button hx-delete="{% url 'delete-comment' comment.id %}" 
                                                hx-confirm="Are you sure you want delete comment"
                                                class="btn btn-link"><i class="fa-solid fa-trash" style="color: #f2075a;"></i>
                                                </button>
                                        </p>
                                    </div>
                                {% else %}
                                    <div class="comment" >
                                        <a href="{% url 'profile' comment.owner %}"><samp>@{{comment.owner}}</samp></a>
                                        <p>{{comment.body}}</p>
                                    </div>
                                {% endif %}                              
                            {% endfor %}
                        </div>
                    </div> 
                </div> 
            </div>
        {% endfor %}
    </div>

    
        <div class="suggestions mt-5"> 
            {% include 'core/partials/follow_suggestions.html' %}
        </div>  
    

 
        {% include 'core/partials/chat_suggestions.html' %}
    

</div>


{% include 'core/partials/create_post.html' %}



{{request.user.id|json_script:"request-user-id"}}
{{request.user.username|json_script:"request-user-username"}}

<script src="{% static 'js/notifications.js' %}"></script>



{% endblock content %}
    

templates/core/post_detail.html
{% extends '_base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'style/post_detail.css' %}">
{% endblock css %}

{% block content %}
<div class="post-container">
    <div class="cards">
        <div class="card-item card mt-5 mb-3">
            <div>
                {% if request.user == post.user %}
                    <button class="btn btn-link dropdown-toggle " type="button" data-bs-toggle="dropdown" aria-expanded="false"><i class="fa-solid fa-ellipsis"></i></button>
                    <ul class="dropdown-menu dropdown-menu-dark">
                        <li>
                            <button hx-delete="{% url 'delete-post' post.id %}?next={% url 'profile' request.user %}" 
                                    hx-confirm="Are you sure you want to delete this post?"
                                    class="dropdown-item" >Delete post</button>
                        </li>
                        <li>
                            <a class="dropdown-item" href="{% url 'update-post' post.id %}">Update post</a>
                        </li>
                    </ul>
                {% endif %}
                <img src="{{post.image.url}}" class="card-img-top" alt="..."> 
                  
               
            </div>
            <div class="card-body">
                <div class="d-flex justify-content-between ">
                    <h5 class="card-title  "><a href="{% url 'profile' post.user.username %}">@{{post.user.username}} </a>| {{post.title}}</h5>
                    <div class="d-flex justify-content-between ">
                        <div class=" d-flex justify-content-end text-center">
                            

                            <ul class="list-inline mb-0">
                                <form hx-post="{% url 'home' %}">
                                    <input type="hidden" name="post_id" value="{{post.id}}">
                                    {% if is_post_liked %}
                                        <li class="list-inline-item">
                                            <button type="submit" class="btn btn-link "><small class="text-muted"> <i class="fa-solid fa-heart fa-xl " style="color: #f2075a;"></i></small></button><h6 class="">{{likes.count}}</h6>
                                        </li>
                                    {% else %}
                                        <li class="list-inline-item">
                                            <button type="submit" class="btn btn-link" ><small class="text-muted"> <i class="fa-regular fa-heart fa-xl" style="color: #f2075a;"></i></small></button><h6 class="font-weight-bold mb-0 d-block">{{likes.count}}</h6>
                                        </li>
                                    {% endif %}
                                </form>            
                            </ul>
                        </div>
                    </div>   
                </div>

                <p class="card-text mt-3">{{post.description}}</p>
                <p class="card-text"><small class="text-body-secondary">{{post.created}}</small></p>
                <hr>
                    <!-- comments -->
                <div id="comment-section "> 
                    <div class="d-flex justify-content-between">
                        <img id="profile_img" src="{{profile.image.url}}" alt="">
                        <form hx-post="{% url 'comment' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="post_id" value="{{post.id}}">
                            <input class="comment_input" type="text" name="body" placeholder="write your comment..." required>
                            <button type="submit" class="btn btn-link "><i class="fa-regular fa-paper-plane"></i></button>
                        </form>
                    </div>
                    
                    {% for comment in comments|slice:"10" %}                   
                        {% if comment.owner == request.user  %}
                           <div class="comment" >
                                <samp >@{{comment.owner}}</samp>
                                <p>{{comment.body}}
                                        <button hx-delete="{% url 'delete-comment' comment.id %}" 
                                                hx-confirm="Are you sure you want delete comment"
                                                class="btn btn-link"><i class="fa-solid fa-trash" style="color: #f2075a;"></i>
                                        </button>
                                </p>
                            </div>
                        {% else %}
                            <div class="comment" >
                                <samp >@{{comment.owner}}</samp>
                                <p>{{comment.body}}</p>
                            </div>
                        {% endif %}                              
                    {% endfor %}
                </div>
            </div> 
        </div> 
    </div>
</div>
    
{% endblock content %}
    

templates/core/settings.html
{% extends '_base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}


{% block content %}
<div class="d-flex justify-content-center">
    <div class="card mt-3 " style="width: 30rem;">
        <div class="card-body">
        <h5 class="card-title">Edit Profile</h5>
        <div id="image_box">
            <img  src="{{profile.image.url}}" class="card-img-top " alt="...">
        </div>
        <form  method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <div  id="image" class="forms-control {% if field.errors %} errors {% endif %} ">
                <label>{{ form.image.label_tag }}</label>
                {{ form.image.errors }}
                {% render_field form.image class="form-control"  name="image" id="id_image"%}
            </div>
  
            <div class="forms-control {% if field.errors %} errors {% endif %} ">
                <label>{{ form.bio.label_tag }}</label>
                {{ form.bio.errors }}
                {% render_field form.bio class="form-control"  name="bio" id="id_bio"%}
            </div>
            
            <div  class="forms-control {% if field.errors %} errors {% endif %} ">
                <label>{{ form.location.label_tag }}</label>
                {{ form.location.errors }}
                {% render_field form.location class="form-control"  name="location" id="id_location"%}
            </div>
  
            <button type="submit" class="btn btn-success mt-2">Update Profile</button>
        </form>
        
        </div>
    </div>
</div>

<script>
    const input = document.getElementById("id_image")
    const imageBox = document.getElementById("image_box")
    const csrf = document.getElementsByName("csrfmiddelwaretoken")

    input.addEventListener("change", ()=>{
      const img_data = input.files[0]
        const url = URL.createObjectURL(img_data)
        imageBox.innerHTML = `<img src="${url}" id="image" width=450px >`
      
    })


  </script>
{% endblock content %}

templates/core/update-post.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}
{% load static  %}
{% load widget_tweaks %}


{% block css %}
    <link rel="stylesheet" href="{% static 'style/update_post.css' %}">
{% endblock css %}
    

{% block content %}

<div class="container">
    <div class="card" style="width: 35rem;">
        <div id="image_box">
        <img  src="{{post.image.url}}" class="card-img-top " alt="...">
        </div>
        <div class="card-body">
        <h5 class="card-title">Card title</h5>
        
        <form  method="POST" enctype="multipart/form-data" >
            {% csrf_token %}
            <div  id="image" class="forms-control {% if field.errors %} errors {% endif %} ">
                <label>{{ form.image.label_tag }}</label>
                {{ form.image.errors }}
                {% render_field form.image class="form-control"  name="image" id="id_image"%}
            </div>
            <div class="forms-control {% if field.errors %} errors {% endif %} ">
                <label>{{ form.title.label_tag }}</label>
                {{ form.title.errors }}
                {% render_field form.title class="form-control"  name="title" id="id_title"%}
            </div>
            
            <div  class="forms-control {% if field.errors %} errors {% endif %} ">
                <label>{{ form.description.label_tag }}</label>
                {{ form.description.errors }}
                {% render_field form.description class="form-control"  name="description" id="id_description"%}
            </div>
            
            
            <button type="submit" class="btn btn-success mt-2">Update Post</button>
          </form>
        </div>
    </div>
</div>
<script>

    
    
    const input = document.getElementById("id_image")
    const imageBox = document.getElementById("image_box")
    const csrf = document.getElementsByName("csrfmiddelwaretoken")

    input.addEventListener("change", ()=>{
        console.log("chaced")

        const img_data = input.files[0]
        const url = URL.createObjectURL(img_data)
        imageBox.innerHTML = `<img src="${url}" id="image" width=558px height=500px>`

    })
</script>
    
{% endblock content %}

    
    
    
    